services:
  slottets-sqlserver:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      slottets-dockernet:
        ipv4_address: 10.29.0.2

  build-stage:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-stage
    restart: "no"
    networks:
      slottets-dockernet:
        ipv4_address: 10.29.0.5

  tests-stage:  
    build:
      context: .
      dockerfile: Dockerfile
      target: tests-stage
    depends_on:
      slottets-sqlserver:
        condition: service_started
    working_dir: /workspace
    volumes:
      - ./TestResults:/artifacts/TestResults
    networks:
      slottets-dockernet: 
        ipv4_address: 10.29.0.10
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - ASPNETCORE_ENVIRONMENT=Development
      - DOCKER_DOTNET_TEST=true
    restart: "no"

  publish-stage:
    build:
      context: .
      dockerfile: Dockerfile
      target: publish-stage
    depends_on:
      tests-stage:
        condition: service_completed_successfully
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: no

  final-stage:
    build:
      context: .
      dockerfile: Dockerfile
      target: final-stage
    depends_on:
      publish-stage:
        condition: service_completed_successfully
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    # entrypoint: ["dotnet", "Slottet.CareManagement.dll"]
    ports:
      - "5000:5000"
    networks:
      slottets-dockernet:
        ipv4_address: 10.29.0.30
    restart: "no"

volumes:
  mysql_data:

networks:
  slottets-dockernet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.29.0.0/24
